---
title: "Data Resources"
date: last-modified
date-format: medium
---

This document contains a number of resources that will (hopefully) assist you in locating data. Finding useable data is not always easy, but hopefully this will serve as a useful launching point for you.

------------------------------------------------------------------------

## Foundation, Demographic, Socioeconomic, Environmental Spatial Data

Please note that I have not worked with data from all of these sources, so I might not be able to offer much help with troubleshooting any issues you encounter when searching or downloading from some of the websites listed. Also, I did not recheck the links in the most recent update.

##### Resources

-   [US Census (Census and American Community Survey data joined to spatial data \[TIGER\]](https://www.census.gov/geo/maps-data/data/tiger-data.html)\
-   [National Historical Geographic Information System (NHGIS)](https://www.nhgis.org/) (great resource for current and historical census-based data for the US, includes both tabular and spatial data)\
-   [USGS National Map (Environmental data, infrastructure data, and aerial imagery)](https://viewer.nationalmap.gov/basic/)\
-   [USGS National Map FTP site](ftp://rockyftp.cr.usgs.gov/vdelivery/Datasets/Staged/) (enter as guest if prompted)\
-   [USGS Earth Explorer](https://earthexplorer.usgs.gov/) (Digital orthorectified aerial photos, Landsat satellite data, Digital Elevation Models \[DEM\], this site is a bit clunky to use, but a great resource)\
-   [Adding data from ArcGIS Online](http://desktop.arcgis.com/en/arcmap/latest/map/working-with-arcmap/adding-data-from-arcgis-online.htm) (data are not always “downloadable”)\
-   [US National Land Cover Database](https://www.mrlc.gov/nlcd2011.php)
-   [US Data from Data.gov](https://www.data.gov/) (A lot of data, but spatial data can be a bit difficult locate)
-   [US SSURGO (soils) and Hydrography](https://datagateway.nrcs.usda.gov/GDGHome_DirectDownLoad.aspx)
-   [PRISM climate data](http://prism.oregonstate.edu/)
-   [Climate Data Online from NOAA](https://www.ncdc.noaa.gov/cdo-web/)
-   [Data from USDA](https://www.nrcs.usda.gov/wps/portal/nrcs/main/national/technical/nra/dma/) (includes climate, natural resources inventory, watersheds, easements, and more)
-   [Wiki Page for downloading data from OpenStreetMap](https://wiki.openstreetmap.org/wiki/Downloading_data)
-   [Global Administrative Boundaries](http://www.gadm.org/) (multiple levels of administrative bounds for most countries)
-   [DIVA GIS](http://www.diva-gis.org/gdata) (administrative, infrastructure, natural, and population data for most countries)
-   [LandScan Gridded Population data](http://web.ornl.gov/sci/landscan/landscan_data_avail.shtml) (work with UNC library to download)
-   [Gridded Population of the World](http://sedac.ciesin.columbia.edu/data/collection/gpw-v3)
-   [Air Quality System (AQS) Ambient Air Pollution data](https://www.epa.gov/outdoor-air-quality-data)

<br>

##### Google Search Tips For Spatial Data

If you're trying to find spatial data, try a search string that is extremely detailed such as, `study area gis data download`. One semi-important observation that I have made is the importance of including the word `download` in your search string. For example, you could search for, `botswana gis data download`.

------------------------------------------------------------------------

## Health Data

Please note that I have not worked with data from all of these sources, so I might not be able to offer much help with troubleshooting any issues you encounter when searching or downloading from some of the websites listed. Also, I did not recheck the links in the most recent update.

##### Resources

-   [CDC Places Data Repository ](https://www.cdc.gov/places/index.html)
-   WHO, Global Health Observatory Data Repository, [By Theme](http://apps.who.int/gho/data/node.home), [By Country](https://www.who.int/gho/countries/en/)
-   [WHO, Mortality Database](http://apps.who.int/healthinfo/statistics/mortality/whodpms/)
-   [US National Center for Health Statistics (NCHS)](https://www.cdc.gov/nchs/data_access/ftp_data.htm) (mostly survey data)
-   [US Health Resources and Services Administration Data Warehouse](https://data.hrsa.gov/)
-   [National Information Center on Health Services Research and Health Care Technology (NICHSR) List of Databases/Repositories](https://hsric.nlm.nih.gov/hsric_public/#164Databases/Repositories) (You will have to go to each and actually find the useable data. I have used a few of the data sources on this list, and navigating their website to get to the data download can be somewhat tedious. This could be a good place to begin your search though.)

<br>

## Consolidated Data Portals

These data portals have fantastic integrated resources for various health, geographic and other demographic, social data etc. If you absolutely dont have any data or project idea that you are interested in, I encourage you to instead use these portals. You have free access to these datasets through USC!

##### Resources

-   [Policy Map ](https://www.policymap.com)
-   [Social Explorer](https://www.socialexplorer.com/home)
-   [ArcGIS Living Atlas](https://livingatlas.arcgis.com/en/home/) 
<br>

## USC Library

And finally, dont forget your own USC library which has several tremendous resources!

-   [Geography Data Guide](https://guides.library.sc.edu/geography/datamaps)
-   [Data Sets and Statistics Guide](https://guides.library.sc.edu/data-and-statistics)

<br>

##### Google Search Tips For Health Data

If you're trying to find health related data, remember that it pretty unlikely that you will find the health data as a spatial data layer. Try a search such as, `study area health data statistics`. For example, `michigan health data statistics`. Other strings can be used such as, `michigan reportable diseases data statistics`.

If you are study a place in the US, you may want to try to include a "geography" identifer in the search, such as `maryland county health data statistics`, which turned up [this link](https://health.maryland.gov/talbotcounty/Pages/Data.aspx) and [this link](https://health.maryland.gov/vsa/Pages/reports.aspx) which both appear very promising.

If you've already found spatial data and are trying to locate tabular data for a particular subject, use a search string with the word table and the geographic resolution (unit) of your spatial data included, e.g., `study area topic unit table`. For example, you could search for, `england vaccination local authorities table`.

You can also try this type of search for "country or region" data and add the government entity that would likely collect or distribute the data. For example, you could search for something similar to, `Ecuador ministry of health statistics data`.

------------------------------------------------------------------------

#### [Google Dataset Search (link)](https://toolbox.google.com/datasetsearch)

------------------------------------------------------------------------

#### Other Data

Please note that I have not worked with data from all of these sources, so I might not be able to offer much help with troubleshooting any issues you encounter when searching or downloading from some of the websites listed. Also, I did not recheck the links in the most recent update.

-   [Datasets for Data Mining and Data Science](https://www.kdnuggets.com/datasets/index.html) (a lot of links here!)\
-   [Data: Government, State, City, Local and Public](https://www.kdnuggets.com/datasets/government-local-public.html) (numerous links here!)\
-   [Data: APIs, Hubs, Marketplaces, and Platforms](https://www.kdnuggets.com/datasets/api-hub-marketplace-platform.html) (numerous links here!)

------------------------------------------------------------------------
