---
title: 'GEOG 510: Assignment #4'
author:
- Spatial Regression, 150 points points \newline
- GEOG 510, GIS & Spatial Analysis in Public Health \newline
- Due by **April 30, 2026**
- Varun Goel
date: 'Updated: `r format(Sys.Date(), "%B %d, %Y")`'
output:
  html_document:
    theme: flatly
    highlight: null
    mathjax: null
---

```{css, echo=FALSE}
a {
  color: royalblue;
}

a:hover {
  color: darkorange;
}

div.highlightblock { 
 background-color: #e0f0ff; 
 padding: 10px 10px 3px 10px;
}
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(kableExtra)
```

------------------------------------------------------------------------

This assignment is split into two parts. In the first part of this assignment, you will be working with hospital utilization (Zip Code level polygon data) to conduct a basic spatial regression analysis in GeoDa. In the second part, you will be asked to formulate a question for your final project that can be asked through using multiple/Spatial Regression. You already completed Q 13 and Q 14 for part 2 in class so I will award you the 30 points even if you do not have your DAG handy. However I do want you to think about Q 15 for your final project. Please at least skim through the entire assignment document before beginning.

On your computer, create a folder for Assignment #4 and a folder (inside of that one) to store data. [Download GEOG510_assignment4_data.zip from here](https://drive.google.com/file/d/1CQFKE0ODxHb6TQXEHuQQfhPZRo_c6k1A/view?usp=sharing) into the data folder and then unzip the contents.

For the assignment, create a single document using some form of word processing software (Microsoft Word is preferred). Include your name, GEOG 510, and Assignment #4 at the top of the document. Answer/complete each of the questions/tasks below. Copy/paste graphics directly into the document where applicable.

Please save the file using the following naming format, **userid_assignment4.docx**. For example, my file would be **vgoel_assignment4.docx**. Please follow the file naming format for your document. Upload your assignment document to your OneDrive folder when complete.

------------------------------------------------------------------------

## Part #1: Regression Analysis of Hospital Utilization Rates (110 points)

In this analysis, you will be exploring the underlying factors that affect variations in hospital utilization (at a Zip Code level) in Michigan (data courtesy Dr. Paul Delamater). The main question is whether the availability of hospital beds (measured as spatial accessibility) affected hospital utilization while controlling for other potential confounders that could also affect variation in hospital utilization. You will be walking through a multiple spatial regression analysis in GeoDa to help answer this.

------------------------------------------------------------------------

#### Import data and Interpolation

1.  Open QGIS and add the mi_zip_util layer from the MI_Zip_Util.gpkg in your `GEOG510_assignment4_data` folder. *NOTE: the next steps might take a bit of time. GeoDa can save your work in a Project file. It might be a good idea to create one and save as you go.*

2.  Open the attribute table to view the fields included in the data layer. They are defined as follows:

    -   **CL895**: The ID associated with each observation. Some of the Zip Codes in MI were grouped with neighboring Zip Codes prior to the analysis (this was a data issue in the hospitalization data), so they do not have traditional Zip Code numbers. However, this is ultimately Zip Code level data.
    -   **AAPDr**: The Age-adjusted Patient Day rate. This is our dependent (Y) variable. This is total days spent in the hospital for residents of each Zip Code divided by the total number of residents in each Zip Code. The values were then age-adjusted using an indirect standardization approach.
    -   **POP**: The total Population of each Zip Code.
    -   **E2SFCA**: (MAIN X VARIABLE) The measure of spatial accessibility (or availability) of hospital beds available to residents of each region. It is called the Enhanced 2 Step Floating Catchment Area metric, and its calculation integrates supply (hospital beds), potential demand (Population), and the distance separating supply and demand locations. Higher values indicate higher spatial accessibility (availability). We will cover this metric in more detail later in our course.
    -   **HINS0064**: The proportion of the Population aged 0-64 that has some form of health insurance. This age group is often used for health insurance because, theoretically, everyone in the US over the age of 65 has health insurance via Medicare.
    -   **EDBApl**: The proportion of the Population aged 25 and above that has a bachelor's degree or higher.
    -   **FEMPCT**: The proportion of the Population that is female.
    -   **WHITEPCT**: The proportion of the Population that is white.
    -   **POPDENS**: The Population density in units of people per km^2^.

3.  Prior to performing any multiple regression, we should check for correlation among our independent variables (unless the model you are using specifically accounts for this). If there is correlation present, our independent variables aren't truly “independent” and will cause issues in the results (called multicollinearity). We can evaluate the potential for multicollinearity prior to regression by calculating the Pearson's R of the variables, or we can evaluate it after the regression by calculating the variance inflation factor (VIF) of each variable.

::: highlightblock
There are a number of "rules of thumb" for what is an allowable level of multicollinearity in a regression model (discussed in Lecture #21). I tend to use both Pearson's R and VIF. My own personal rules of thumb are much more strict than others I've seen in the literature. **Personally, I only feel truly comfortable including X variables in a model that have a pairwise Pearson's R value of less than 0.5 and/or a VIF value of less than 2.** However, I let these stretch somewhat depending on each project, especially if there is strong justification and theory behind the variable.
:::

<p>

<br>

4.  The Pearson's R values (Correlation_matrix.csv) and the VIF values (VIF_values.csv) for the potential independent variables are included in the `GEOG510_assignment4_data` folder folder. The R code I used to do these calculations is named Assess_multicollinearity.R and is located in the `code` folder. Examine the Pearson's R and VIF values for all models and use them to answer the following question.

------------------------------------------------------------------------

##### [Question #1: Dr. Goel decided that you will use the following independent variables in your regression analysis – POP, E2SFCA, HINS0064, EDBApl, FEMPCT, WHITEPCT. In 3-5 sentences, explain how he came to this decision and point out instances (specifically, tell which variables or which model) in which he disregarded his personal rules of thumb (use NOTE above).]{style="color: green;"}

------------------------------------------------------------------------

5.  You can now close the correlation matrix and VIF tables. Navigate back to GeoDa (with MI_Zip_Util.gpkg loaded). When working with spatial data and regression in GeoDa, in order to evaluate whether the residuals of a regression model are spatially autocorrelated, you must first define the neighbors and their weights. Click on Tools \| Weights Manager or click the “W” button on the main menu bar. Click Create. Use CL895 (zipcode equivalent) as the ID Variable. Use Queen contiguity for the weights. Name them MI_ZIP_Util_queen.gal and store in the `GEOG510_assignment4_data` folder. After you create the weights, you can close the Weights Manager.

6.  You will now perform a regular OLS regression, which will also provide you diagnostic information about whether or not you should use a spatial regression model. In the top menu, click Regression \| Regression or click the REG button on the main menu bar. In the dialog box, add **AAPDr** as the Dependent Variable. Add the variables from Question #1 (only) as the Covariates. Make sure MI_ZIP_Util.gal is selected as the Weights File. In the Models area, make sure that Classic is selected. Click Run.

7.  Review the Regression output, which should appear in a new window called Regression Report. Some things of note, the model is significant `[Prob(F-statistic)]`; the coefficients are all significant except for POP; uh oh... the Multicollinearity Condition Number (MCN) is extremely high (much higher than the recommendation of 30). Go back to the Regression window and remove HINS0064 from the covariates, then click Run. Note the MCN value is still too high. Now, remove FEMPCT from the covariates, then click Run.

::: highlightblock
There are a number of ways to deal with (X) variables that are causing multicollinearity in a regression model. Removal of variables from the model is just one of them. In this case, I determined which variables to remove (to get a decent MCN) via a trial and error process and examination of the bivariate correlation matrix. However, other solutions are Stepwise Regression (automated variable removal), Principal Components Analysis (to extract “components” that capture the variation in a set of X variables), and others. Another method that I use a lot is to rely on Directed Acyclic Graphs (DAGs) to get a set of minimum confounders to include in the model. The DAGs rely a lot on theory and are a cornerstone of epidemiological research. Please let me know if you need more information/resources especially for your final projects.
:::

<p>

------------------------------------------------------------------------

##### [Question #2: What was the Multicollinearity Condition Number for the 2nd and 3rd OLS regressions from Step 7?]{style="color: green;"}

------------------------------------------------------------------------

8.  Now, we have a model that meets our requirement of independent X variables. Now, let's examine whether the residuals have spatial autocorrelation. Scroll down in the regression output and look for DIAGNOSTICS FOR SPATIAL DEPENDENCE. Here you will find the Moran's I test of the regression residuals.

------------------------------------------------------------------------

##### [Question #3: Do you need to run a spatial regression? \[the answer is Yes\]. In 2-3 sentences, explain why this is the case (using evidence from the OLS output).]{style="color: green;"}

------------------------------------------------------------------------

##### [Question #4: Copy/paste the summary results of your 3rd OLS regression from Step 7 into your lab document. Make sure that the font stays as Courier!]{style="color: green;"}

------------------------------------------------------------------------

##### [Question #5: Which type of spatial regression model should you run based on a) theory and b) the diagnostics (see lecture slides or GeoDa handbook). Provide 1-3 sentences for each. Keep in mind that hospitalizations are not contagious.]{style="color: green;"}

------------------------------------------------------------------------

9.  In the regression window, change from a Classic model to a Spatial Error model. Click Run. Examine the results in the Regression Report window. The output we will focus on is AIC (Akaike info criterion). Note that the AIC value -1,249.99 is lower than the AIC value from the OLS model -945.992 indicating a better model fit. Also, note that Lambda (the spatial error coefficient) is highly significant.

------------------------------------------------------------------------

##### [Question #6: Copy/paste the summary results of Spatial Error model into your lab document. Make sure that the font stays as Courier!]{style="color: green;"}

------------------------------------------------------------------------

##### [Question #7: Describe how the coefficient values changed in the spatial error model (compared to the 3rd OLS model). Are the effect sizes bigger/smaller? Is there anything notable that changed in the significance of the coefficients?]{style="color: green;"}

------------------------------------------------------------------------

10. Write the predicted values, the residuals, and prediction errors from your spatial error model to your attribute table by clicking on the Save to Table button in the Regression window (keep the default names). After you have saved the values to your table, run a Moran's I on the residuals by navigating to Space \| Univariate Moran's I in the top menu. Choose ERR_RESIDU as the variable.

::: highlightblock
While writing this assignment, I found out that the authors of GeoDa say that generating a pseudo P-value for the Moran's I results of regression residuals is not an acceptable approach. Thus, to evaluate remaining spatial autocorrelation in the residuals, we will use the magnitude of the Moran's I value, rather than the pseudo P-value.
:::

------------------------------------------------------------------------

##### [Question #8: What is the Moran's I value of the residuals from the Spatial Error model? Is this a small/medium/large amount of remaining spatial autocorrelation?]{style="color: green;"}

------------------------------------------------------------------------

11. Now, run a Spatial Lag regression model using the same set of variables. In the Regression window, change to a Spatial Lag model and click Run. Save the results to your attribute table. The spatial lag parameter is Rho, which is identified as W_AAPDr in the output.

------------------------------------------------------------------------

##### [Question #9: Copy/paste the summary results of Spatial Lag model into your lab document. Make sure that the font stays as Courier!]{style="color: green;"}

------------------------------------------------------------------------

##### [Question #10: Based on AIC, which model (Spatial Lag or Spatial Error) fits the observed hospitalization data better? (See Step #9 on AIC interpretation)]{style="color: green;"}

------------------------------------------------------------------------

##### [Question #11: What is the Moran's I value of the residuals of the Spatial Lag model? Is this a small/medium/large amount of remaining spatial autocorrelation?]{style="color: green;"}

------------------------------------------------------------------------

12. Unfortunately, similar to many health-related models that use observed data, the residuals from both the spatial error and lag models both fail the tests of normality and heteroscedasticity. This is extremely common with ecological (aggregated) spatial data. In this case, we will assume that these violations **do not** undermine our ability to make inference from the results of the model.

::: highlightblock
**Extra Credit Opportunity: 10 points** Figure out in GeoDa how to create a histogram of your regression residuals to evaluate normality and and a scatterplot to evaluate heteroscedasticity in the residuals. Paste the graphics directly into your assignment document. Make sure that the graphics are large enough that I can evaluate that you have plotted the correct values.
:::

------------------------------------------------------------------------

##### **Question #12**: Going back to the original research question, does the availability of hospital beds affect hospital utilization (while controlling for other factors)? What is the direction of this relationship? Use the output of your regression analysis to justify/explain your answer (limit your explanation to the analysis we performed).

------------------------------------------------------------------------

13. Save your project and close GeoDa.

------------------------------------------------------------------------

## Part #2: Thinking about regression for your project question (40 points)

While it is not necessary to implement a regression analysis for your final projects, regression can be a powerful tool to test hypotheses related to spatial processes driving the observed spatial patterns of your health outcoome. In this part, you are asked to conceptualize what a regression analysis may look like for you, so that you can more confidently implement it in your final projects if you choose to.

##### [Question #13: Frame your main research question in the context of an independent (x) and dependent (Y) variable. For example, my main question is to look at how does daily average temperature (X variable) impact percentage of people with mental health distress in each censusc tract of South Carolina (Y variable). Be as specific as you can so that you will have a better idea of what exact data you need to have.]{style="color: green;"}

##### [Question #14: Name atleast 3 potential confounders/other independent variables (other than Age, Sex, and population) that you would include in your analysis. Age, Sex, and populationare almost always variables in many health analysis, so I want you to think beyond them. Also explain why do you think they may be potential confounders to be added. Be as specific as you can so that you will have a better idea of what exact data you need to have.]{style="color: green;"}

##### [Question #15: Think about the potential motivation of why a spatial regression may be important for your question, in the context of 1st order and 2nd order spatial analysis. In 3-5 sentences, explain the motivation/reasoning behind why you would want to use one spatial regression and if so, which one ( or both, or not? Link your reasoning to the type of 1st order and 2nd order spatial processes that may be driving your research question for your analysis.]{style="color: green;"}

::: highlightblock
**Extra Credit Opportunity: upto 40 points** I will grant upto 40 points if you actually conduct a regression analysis for your own final project data. This will be based on the sophistication and accuracy of your analysis, but even a non-horrible simple OLS regression will fetch 10 points.
:::

**If you have any questions, do not hesitate to ask!**

------------------------------------------------------------------------

### Deliverables

Upload your answer document to OneDrive.

------------------------------------------------------------------------
