---
title: "Geog 510: Assignment #2"
author:
- Working with Spatial Data, **125 points** \newline
- Due before class on Thursday, **Feb 26, 2026**
- GEOG 510, GIS and Spatial Analysis for Public Health \newline
- Varun Goel
date: last-modified
date-format: medium
output:
  html_document:
    theme: flatly
    toc: yes
    toc_float: yes
    toc_depth: 3
---

```{css, echo=FALSE}
a {
  color: royalblue;
}

a:hover {
  color: darkorange;
}

div.highlightblock { 
 background-color: #e0f0ff; 
 padding: 10px 10px 3px 10px;
}
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(kableExtra)
library(tidyverse)
```

------------------------------------------------------------------------

This assignment is split into two main portions. For the first (and larger) part of the assignment, you will be working through a number of tasks related to importing, pre-processing, and summarizing data. In this part, you will also be creating two maps in an effort for you to begin developing this skill. For the second part, you will be searching for data (related to your topic of interest) and begin the process of making sure that it is ready for use in a GIS.

On your computer, create a folder for Assignment #2 and a folder (inside of that one) to store data. [Download GEOG510_assignment2_data.zip from here](https://drive.google.com/file/d/1DN3Snj0QVuJzP1WBqRfZrKz7jlY29bcn/view?usp=share_link) into the data folder and then unzip the contents.

Create a single document using some form of word processing software (Microsoft Word is preferred). Include your name, GEOG 510, and Assignment #2 at the top of the document. Answer/complete each of the questions/tasks below.

[**Note: There are 4 answerable questions for the word document. While you do not need to copy/paste anything related to rest of the tasks in the document, you can copy/paste graphics or comments in the document to support your work**]{style="color: #800000;"}

Please save the file using the following naming format, **userid_assignment2.docx**. For example, my file would be **vgoel_assignment2.docx**. Please follow the file naming format for your document, as this really helps me to stay organized and grade more efficiently. If you do not follow this correctly, I will deduct **10 points** from your assignment for not reading the instructions properly. Upload your assignment document to your *relevant checkpoint assignments folder in OneDrive*.

When the assignment requires you to create a map, export your completed map as a .pdf document using the following naming format, **userid_assignment2_map#.pdf. For example, the second map I create for this assignment would be** vgoel_assignment2_map2.pdf\*\*, and so on. Please follow the file naming format for your maps as well. Upload the maps you create in this lab as separate .pdf documents.

------------------------------------------------------------------------

## Part #1

### [Geocoding]{.underline}

In the next section, you will be geocoding the location of Michigan acute care hospitals using two different geocoders. Then, you will perform both a table and spatial join to add attribute values to the hospital location data.

------------------------------------------------------------------------

#### Geocoding using an online geocoding service

The US Census Bureau provides a free, online geocoder for addresses in the US, Puerto Rico, and the US Island Areas. You can geocode up to 10,000 addresses per submission.

1.  Navigate to the [Census Geocoder page](https://geocoding.geo.census.gov/geocoder/). In the top menu, choose **Find Locations \| Batch Address Processing**. There is a [specific format you need to follow when submitting data](https://www2.census.gov/geo/pdfs/maps-data/data/Census_Geocoder_User_Guide.pdf) (a csv file must **not** have a header row and must have the following fields: ID, Address, City, State, and Zip). Fortunately for you, I am a kind professor and have provided you with a file that conforms to this format. Click on the Browse button, and then choose MIhospitals.csv. The Benchmark should be Public_AR_Current. Click the Get Results button and save your geocoded output file in your data folder as MIhospitals_census_geocoded.csv.

------------------------------------------------------------------------

#### Import X,Y data into QGIS

Now, you will convert the tabular data (containing the geocoded locations from the Census Bureau) into a spatial data file in QGIS. Remember, tables are not spatial data files... even if they contain spatial information. Some processing is required to define the numbers found in the tables as coordinate locations on Earth's surface.

2.  The output file from the US Census requires some light data wrangling before it can be read/used in QGIS. Open MIhospitals_census_geocoded.csv using Excel or some other spreadsheet-like software (but the instructions are based on Excel).

[**Q1. How many records were not geocoded at all? Write down your answer in your word file**]{style="color: #800000;"}

3.  **Insert two new (blank) columns to the right of the field** containing the coordinate locations (the coordinate locations should be in the *F* column if viewing the file in Excel). In the first row, in the first blank cell (cell G1), type `=TEXTSPLIT(F1, ",")`, then hit the return key. If done correctly, G1 should contain the value before the comma in F1 and H1 should contain the value after the comma in F1. Copy/paste to the rest of the rows. Delete the formula from **all rows** without a value in F, e.g., F4, F79, etc.

4.  Add a blank row above the first row and insert the following values in the new row (this will function as the header row or column names when importing):

FAC_ID,ADDRESS,GC_RESULT,GC_TYPE,GC_ADDRESS,GC_LOCATION,LONGITUDE,LATITUDE,TIGER_ID,TIGER_SIDE

5.  Save the file and close Excel.

6.  Open QGIS and create a new project. Open the Data Source Manager (button on the menu bar or in the top menu Layer \| Data Source Manager). In the Data Source Manager, click on **Delimited Text** in the menu on the left. Use the following options:

    -   For File name, use the three dots button and navigate to Mihospitals_census_geocoded.csv
    -   Under Geometry Definition, make sure the LONGITUDE is selected for X field and LATITUDE is selected for Y field. For Geometry CRS, choose EPSG:4326 - WGS 84 (this is the CRS used by the US Census Bureau for the results).
    -   Leave all other options on their default settings, then click Add.

You should now see the points displayed in the map canvas and have a point layer called MIhospitals_census_geocoded in the Layers panel. **This layer is simply held in temporary memory**; thus, it is good practice to actually create a new permanent file that will store this layer.

7.  To do so, right click on MIhospitals_census_geocoded and choose Export \| Save Features As. Save the file as MIhospitals_census_geocoded.gpkg in your correct folder (it should be added to the Layers panel after you click OK). Remove the "csv version" of MIhospitals_census_geocoded from the Layers panel.

------------------------------------------------------------------------

#### Geocoding inside of QGIS using MMQGIS

Next, you will geocode the same original data using QGIS.

8.  Use the instructions provided in the QGIS Plugins and Geocoding In Class Demonstration (#4) to install and activate the MMQGIS plugin.

9.  Add MIhospitals_with_header.csv to the Layers panel in QGIS.

10. In the top menu, navigate to MMQGIS \| Geocode \| Geocode CSV with Web Service. Choose MIhospitals_with_header.csv as the input. QGIS attemps to find the correct fields for Address, City, and State (verify this worked). For Web Service, choose OpenStreetMap / Nominatim. For Output File Name, click the little button with three dots and Save As MIhospitals_osm_geocoded.gpkg. For Not Found Output List, Save As MIhospitals_osm_geocoded_notfound.csv. Click Apply. The process will likely take a few minutes to complete (just hold tight until you see the results appear in the Layers panel).

[**Q2: How many records were NOT Geocoded using MMQGIS? Write your answer in the word file.**]{style="color: #800000;"}

11. Add MI_counties to the Layers panel (it's okay if you get a warning about the CRS!... it is just a warning). Arrange the layers so that the county polygons are not covering the points.

12. Change the CRS of the map canvas to Michigan GeoRef (NAD83 / Michigan Oblique Mercator, EPSG:3078).

13. Now would be a good time to save your project file, which saves your progress thus far. Go to Project \| Save As and save your project as assignment2_geocode.qgs.

14. Using the Map Composer, make a map that highlights at least 3-4 locations that are different between the two geocoded results. [Click here for the QGIS tutorial](https://docs.qgis.org/3.34/en/docs/training_manual/map_composer/map_composer.html). Use the following for guidance:

    -   Make sure you choose symbols for the two hospital layers that are distinguishable.
    -   Turn on Labels for MI_osm_geocode layer (use the field, FAC_ID).
    -   Use the layer MI_Counties as the base layer for Michigan (use light fill and line colors)\
    -   Make sure the map has a title, legend, scale bar, north arrow, and your name!
    -   Make sure that you try to make something that looks visually pleasing (colors are good, elements are aligned, layout is balanced, etc).
    -   When complete, export your map using userid_assignment2_map1.pdf.

15. Close the Map Composer. Save your project file, then close QGIS.

------------------------------------------------------------------------

### [Data Pre-processing]{.underline}

We often have to do a number of steps to make our data manageable and mappable. In the next section, you will remove extraneous information from the attribute table of the new spatial features you just created. Then, you will join information from a table to that file and create a map.

16. Open QGIS and create a new project. Add MIhospitals_census_geocoded to the Layers panel. Change the CRS of the map canvas to Michigan GeoRef (NAD83 / Michigan Oblique Mercator, EPSG:3078).

------------------------------------------------------------------------

#### Delete fields in attribute table

**It is very important to note that the next step is a destructive editing step**. It edits the original file and there's no recovering the original information. If you are not sure that you are okay with this, make a copy of the original file first (right click on the layer in the Layers panel and choose Export \| Save Features As).

17. Right click on MIhospitals_census_geocoded and choose Properties. In the menu on the left, choose Fields. Click on the little button that looks like a pencil to toggle editing ON/OFF. Click on the fields that you want to delete (using control/command clicking)... in this case, you can delete GC_ADDRESS, GC_LOCATION, TIGER_ID, and TIGER_SIDE. When ready, click the Delete Field button (with a little red X). Click the button to toggle editing back to OFF. Save your edits. Click OK.

18. Now would be a good time to save your project file, which saves your progress thus far. Go to Project \| Save As and save your project as assignment2_tablejoin.qgs.

------------------------------------------------------------------------

#### Table Join

A table join allows you to merge information from two separate layers/tables based on a common ID value. In QGIS, these can occur between/among spatial and non-spatial data layers. Table joins are one of most common data preparation steps using in GIS.

19. Add MI_hosp_attributes.csv to the Layers panel. This table contains the attributes that you will be joining to the features in the MIhospitals_census_geocoded layer. Open both attribute tables and inspect the available fields. Identify the **key field** you will be using for the join.

20. Right click on MIhospitals_census_geocoded and choose Properties. In the menu on the left, choose Joins. Click on the little green "plus" button at the bottom. For Join Layer, choose MI_hosp_attributes. The **key fields** are the Join field and the Target field. Choose the correct fields for the join. Leave everything else unchanged and click OK.

21. Open the attribute table of MIhospitals_census_geocoded and note the joined fields. If you scroll down in the attribute table, you should notice that some of the hospitals have NULL values in the joined fields. This is because there was not a “matching” or “corresponding” entry for these features in the MI_hosp_attributes.csv file. This is okay for the purposes of this lab. However, it is good practice to always check the output of a table join to ensure that nothing fishy happened during the join. A simple way to do this when you have a lot of features (and you don't feel like manually checking each of them) is to perform an attribute query on one of the joined fields. Close the attribute table.

::: highlightblock
##### Table joins are not permanent

A table join is not a permanent operation. The joined data only exists in temporary memory in QGIS. Sometimes this is a good thing... because you might only need the joined data for a single map or operation. Other times, you might be building a layer that you will need multiple times in the future. To make the join permanent, right click on the layer in the Layer panel and export as a new file.
:::

<br>

You are required to make a Graduated Symbol map of Michigan's hospital sizes. However, QGIS read in the attribute data for the hospitals as "character" data type rather than "numeric" (character data is not recognized as numeric). So, you will calculate a new numeric field for use in mapping.

22. Right click on MIhospitals_census_geocoded and choose Properties. In the menu on the left, choose Fields. Click the Field Calculator button (looks like some colored dots). In the Field Calculator window, make sure Create a new field is selected. In Output field name, put BEDS. In the Expression area, type or copy/paste: `to_real("MI_hosp_attributes_BEDS")`. Click OK.

23. Using the Map Composer, create a Graduated Symbol map of Michigan's hospital sizes using the BEDS field (the number of beds at each hospital). Use the following for guidance:

    -   The entire state should be on the map
    -   Do not use Labels.
    -   Use the layer MI_Counties as the base layer for Michigan.
    -   Make sure the map has a title, legend, scale bar, north arrow, and your name!
    -   Make sure that you try to make something that looks visually pleasing (colors are good, elements are aligned, layout is balanced, etc).
    -   When complete, export your map using userid_assignment2_map2.pdf.

24. Close the Map Composer. Save your project file and then close QGIS.

------------------------------------------------------------------------

#### Spatial Join

A spatial join allows you to transfer attribute information from one spatial layer to another based on shared location. In this section, you will be performing a spatial join to assign population data to a Zip Code layer for mapping purposes. This section also begins the process of illustrating how multiple operations must be performed to complete an analysis.

25. Since you spent a lot of time creating a nice Michigan map layout in the previous section, you should use that hard work and effort again. Open QGIS and navigate to Project \| Open, then open assignment2_tablejoin.qgs. Remove all the layers that were loaded in the Layers panel, then add the MI_zipcodes.gpkg and MI_block_pop.gpkg layers. The Zip Code layer is a polygon layer representing the areal extent of Zip Codes. The Block population layer is a point layer of the Census Block centroids and contains population information in the field POP (note: this layer has a lot of points in it, you may want to make it not visible). Go to Project \| Save As and save the project as assignment2_spatialjoin.qgs.

::: highlightblock
##### Recycling map layouts

To save time, I often spend a lot of time on my first “study area” map, especially if I know that I will be creating numerous maps of the same region. Then, I just reuse that project file and map composition (save with a new name) as a template.
:::

<br>

You will now spatially join the population information in the MI_block_pop layer to the MI_zipcodes layer. This operation uses shared “location” to transfer attributes. In this case, each Zip Code will be receiving population information from the Block points that fall inside it.

26. We need a tool that is available in the Processing Toolbox to join and summarize information simultaneously. To open the Processing Toolbox, in the top menu navigate to View \| Panels \| Processing Toolbox. In the Processing Toolbox, under Vector General, double click on Join Attributes by Location **(summary)**.

27. The Base Layer is the layer that will be "receiving" the information. The Join Layer is the layer providing the information. In this case, the Base Layer should be MI_zipcodes and the Join Layer should be MI_block_pop. Click the little wrench next to the Join Layer and change the option for Invalid feature filtering to Do Not Filter (there are a few Zip Code polygons that may cause this process to fail if not ignored). For Geometric predicate, intersects should be selected (this will assign information for points falling inside each polygon). For Fields to summarise, choose `POP`. For Summaries to Calculate, choose `sum`. Save as a new file, MI_zipcodes_pop.gpkg.

Open the attribute table of MI_zipcodes_pop. Note that there is now a field called POP_sum. This is the sum of the block population points falling in each Zip Code. Now, you will import hospital utilization data, join it to your new Zip Code layer (with population information), and calculate a new field containing the hospital utilization rate (We can call this a rate because it is utilization over a year).

28. Add MI_PD.csv to the Layer panel. The field PD contains the number of patient days spent in a hospital for residents of each Zip Code (measured during a calendar year). A patient day is equal to one person staying one night in the hospital. Use a table join (see Steps 19-20) to join the patient day table to the MI_zipcodes_pop layer you created in the previous step. After the table join, open the attribute table and verify that you now have patient days and population for each Zip Code.

29. Use the Field Calculator to make the utilization rate calculation by dividing the number of patient days by the population for each Zip Code (see Step 22). In the Field Calculator window, make sure Create a new field is selected. In Output field name, put PD_rate. In the Output field type, choose Decimal number. In the Expression area, type or copy/paste: `"MI_PD_PD" / "POP_sum"`. Click OK.

30. Using the Map Layout you already created in the Map Composer, create a Choropleth map of Michigan's patient day utilization rate by Zip Code. Use the utilization rate field that you just calculated (PD_rate). Use the following for guidance:

    -   The entire state should be on the map
    -   Do not use Labels.
    -   Make sure the map has a title, legend, scale bar, north arrow, and your name!
    -   Make sure that you try to make something that looks visually pleasing (colors are good, elements are aligned, layout is balanced, etc).
    -   When complete, export your map using userid_assignment2_map3.pdf.

------------------------------------------------------------------------

## Part #2

### [Data Source Document]{.underline}

Choose a study area that you would like to focus on for your GEOG 510 project. Search for both spatial and non-spatial data (that can be made spatial) for your study area that you can download. These data could be potentially related to the topic you chose for Assignment 1 - but if you do not want to pursue your idea further or if you cannot find data, you may choose a different topic). You will definitely need **administrative boundaries** and **population data**. You will have to find some **health-related data**. Find and download at least 4 data layers (or tables that can become layers) that you think you might use in your project. Use the following guidance:

-   **The data must be downloadable**
-   **At least one** of these layers should be “non-spatial” data that can be spatialized via geocoding, plot X,Y, or table join
-   **At least one** of the layers must be health-related (which does not include administrative boundaries or population demographic or socioeconomic characteristics, but may include non health outcome data such as environmental hazards or health facilities).

[**Q3: Create a table that has basic information about the layers you locate, including filename, data type, and the data source (e.g., link to webpage or downloadable data). Insert this table into your assignment document.**]{style="color: #800000;"}

------------------------------------------------------------------------

### [Make Your Own Map and Describe Process]{.underline}

Create a map from non-spatial data that you find. This will require either Geocode and/or Import X,Y data for addresses/points or performing a table join. Provide a short explanation of why you chose this data, as well as a short but detailed written description of how you went from “downloaded data” to “map”. Describe any interesting spatial patterns or distributions that you see. Remember to follow good design principles in creating your map and include all map elements. When complete, export your map using **userid_assignment2_map4.pdf**. Additionally, export your map using **userid_assignment2_map4.png**.

In the appropriate area on the Piazza discussion board, insert your .png map directly into a post and copy/paste your explanation.

[**Q4: (0-10 points extra credit depending on your answer) In 1-3 sentences each, provide a reflection on the assignment using the following prompts**]{style="color: #800000;"}

-   [**What did you like about this assignment?**]{style="color: #800000;"}
-   [**What aspect of QGIS do you feel more comfortable with as compared to before?**- **What did you most struggle with while working on the assignment** ?]{style="color: #800000;"}
-   [**Do you have any questions/concerns about your final project? I will go through them and help you wherever I can**]{style="color: #800000;"}

------------------------------------------------------------------------

### [Deliverables]{.underline}

-   **Upload your answer document (userid_assignment2.docx) to your OneDrive folder**
-   **Upload your 4 maps (pdf files) to your OneDrive folder**
-   **Post to Piazza Discussion Board post**

------------------------------------------------------------------------
