---
title: 'Interpolation using IDW'
author:
- In Class Exercise \#9 \newline
- GEOG 510, GIS & Spatial Analysis in Public Health \newline
- Varun Goel
- 10 Points
output:
  html_document:
    theme: flatly
    highlight: tango
    mathjax: null
---

```{css, echo=FALSE}
a {
  color: royalblue;
}

a:hover {
  color: darkorange;
}

div.highlightblock { 
 background-color: #e0f0ff; 
 padding: 10px 10px 3px 10px;
}
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

------------------------------------------------------------------------

In this exercise, you will be interpolating PM 2.5 concentrations in Orange, Durham, and Wake counties during June, July, and August 2024. The PM 2.5 data were created using raw air quality monitoring data downloaded from the EPA.

**Note that throughout this document, if I use the term "right click," this means "control click" for Mac users!**

------------------------------------------------------------------------

### Data

1.  Download [GEOG510_ex9_data.zip](https://drive.google.com/file/d/1gy6-IKV8DKjOcgWPkd-qA1MuTmD1bgEz/view?usp=share_link) and unzip.

### Open QGIS

2.  Open QGIS, then open the project file `GEOG510_ex9.qgz`.

### Inverse Distance Weighted (IDW) Interpolation

#### QGIS Algorithm

3.  In the Processing Toolbox, navigate to Interpolation \| IDW interpolation. Use the following parameters (leave everything else unchanged):

    -   sc_pm25_summer_mean as the Vector layer\
    -   `pm25` as the Interpolation attribute (these are the values) \> click the "plus" button
    -   For the Distance Coefficient, use 2 (this is 1 / d^2^)
    -   For the Extent, click the little down arrow and choose Calculate from Layer, then select the sc_counties_proj
    -   Enter 500 (this is 500m, given the CRS of the project) for Pixel size X (and Y) (this is the resolution of the output surface)
    -   Save as a temporary file (rename as **QGIS_IDW_2** when complete)

#### GRASS Algorithm

4.  In the Processing Toolbox, navigate to GRASS \| Vector \| v.surf.idw. Use the following parameters (leave everything else unchanged):

    -   sc_pm25_summer_mean as the Input vector layer\
    -   For the Power parameter, use 2 (this is 1 / d^2^)
    -   `pm25` as the Attribute table column with values to interpolate
    -   For the GRASS GIS 7 region extent, click the little down arrow and choose Calculate from Layer, then select the sc_counties_proj
    -   Enter 500 (this is 500m, given the CRS of the project) for GRASS GIS 7 region cellsize
    -   Save as a temporary file (rename as **GRASS_IDW_2** when complete)

### Calculate Differences

5.  Use the Raster Calculator to calculate the difference between the QGIS IDW output and the GRASS IDW. Give the output layer a readable name.

### Clip Raster to Study Area

6.  Navigate to Raster \| Extraction \| Clip Raster by Mask Layer. Choose the QGIS GRASS IDW Difference layer as the Input layer and sc_counties_proj as the Mask layer. Uncheck "Match the extent of the clipped raster to the extent of the mask layer". Check "Keep resolution of input raster". Everything else can stay on the default values. Click Run. Give the output a readable name.
7.  You might notice that you get an error such as "clipping Error 1: Cutline polygon is invalid" when you run the clipping tool in step 6. This can happen due to some wierd geometries in vector data. To remedy this, you can run the Fix Geometry tool in the Processing toolbox first and then run your analysis on the fixed file. Hope this will help you in your final projects if you run into geometry errors.

### Get Statistics

7.  Get basic statistics about the clipped "differences" layer. In the Processing Toolbox, navigate to Raster analysis \| Raster layer statistics. Choose the differences layer you just created for the Input layer and then click Run. The statistics will be printed in the Log output of the tool window.

8.  Note down the Minimum, Maximum, and Mean difference between the IDW outputs in SC.You will write these down as text in your map that you create below.

### Create Single Map with Multiple "Panels"

9.  Create a new map layout.

10. Add a new map frame with the following properties:

    -   The SC counties layer should be on top, with no fill
    -   The QGIS IDW layer should be displayed
    -   All other layers should be turned off

11. Copy/paste the map frame. On the original map frame, navigate to the Item Properties and scroll down to Layers. Click the button to Lock Layers and then click Lock styles for layers. This will "freeze" the layer as it appears right now. You can now make changes to the map layers and they will only affect the new map frame you just pasted.

12. In the second map frame, display the GRASS IDW layer.

13. Copy/paste a third map frame. In the third frame, display the differences layer.

14. This map does not need to be perfect or polished. Add the max, min, and mean difference values that you noted down in Step 8 on the map as text. Make sure to put in a title and a name.

15. Save the map as "youruserid_ex9_map1.png" and upload to your relevant OneDrive Folder.
