---
title: 'Basic GIS Operations: Field Calculator, Buffer, Select, and Summarize'
author:
- In Class Exercise \#5 \newline
- 30 points
- Due March 1st, 11:59 PM
- GEOG 510, GIS and Spatial Analyis in Public Health \newline
- Varun Goel

output:
  html_document:
    theme: flatly
    highlight: tango
    mathjax: null
---

```{css, echo=FALSE}
a {
  color: royalblue;
}

a:hover {
  color: darkorange;
}

div.highlightblock { 
 background-color: #e0f0ff; 
 padding: 10px 10px 3px 10px;
}
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

------------------------------------------------------------------------

In this **group** (no more than 3-4 in a group) exercise, you will identify the proportion of disadvantaged populations (minority populations and low income populations) who live within 5 miles of a health care facility in South Carolina.

Create a word document named \`youruserid_ex5.docx' to answer the exercise questions. Also write down the names of our group members. Note that while you can collectively discuss/work on answers with your group members, **please submit your document individually**.

**Note that throughout this document, if I use the term "right click," this means "control click" for Mac users!**

------------------------------------------------------------------------

### Download Data

1.  [Download the data here](https://drive.google.com/file/d/1fufMy_HhRTA8i3JBjOo43nKp7KPjBrHJ/view?usp=share_link) and unzip into your relevant geog 510 exercise folder. Add the `tl_2022_45_bg.shp` shapefile in QGIS that contains all **census blockgroups (BGs)** boundaries in South Carolina.

    ### Open QGIS and Add Census Boundary Data

2.  Open QGIS. Start a new project. Note the CRS of the shapefile and whether it a Geographic Coordinate System or a Projected Coordinate System. This will come in handy later.

### Add, Prepare, and Join Demographic Data

3.  In order to know the distribution of how many disadvantaged people are in each census BG, we need to incorporate demographic information in our analysis.

4.  The relevant demographic information is provided in the file `sc_bg_demographics.csv` . **`GeoID`** is a unique census BG identifier, **`total_pop`** = population of each census BG, and **`poc_perc`** = % of disadvantage people in each BG.

5.  As you input the file into QGIS, please **be careful and consider appropriate field types**. Think about which ones need to be a string, integer or decimal. Choosing the correct field types will save you a lot of headache later.

::: highlightblock
[**Field Types**]{.underline}

I recommend using the Data Source Manager in QGIS to read delimited text and assign correct field types to the csv file itself early in the process when you can. But you can also correct them after joining to your geospatial data as needed, although that can sometimes involve a larger number of steps.
:::

[Q1.What field types did you select for your 3 columns of tabular data and why? (1-2 sentences)]{style="color: red;"}

3.  Attach the population information to the census BG file using tabular join. Note that when you conduct a tabular join in QGIS, the joined columns are temporary. To ensure that they are permanent, export the file to a new file named `bg_pop.gpkg.`

::: highglightblock
[**Attribute/Tabular join in MMQGIS**]{.underline}

While you can use the tabular join using the default QGIS option, MMQGIS offers a convenient tabular join option too in ***MMQGIS -\> Combine -\> Attributes Join from CSV File***. However, while it is very convenient, it is not good at reading missing values, and by default assigns those columns as strings (text). Regardless of any joins you use, MAKE SURE TO CHECK YOUR FIELD TYPES AGAIN.
:::

4.  Open the attribute table to ensure that the join was successful, and once you confirm, remove the `sc_bg_demographics file` and the original `tl_2022_45_bg` layers as they are no longer needed.

### Add and Prepare Health Facilities Data

5.  Now add the `scHealth_Facilities.geojson` file to QGIS. You will be asked to choose an appropriate projection transformation formula since the file in WGS 84 GCS as compared to NAD 83 for the census BG file. Choose the first transformation. There are other potentially more accurate transformations too, but since the accuracy for all is between 4m to 1.5m, the choice of transformation does not matter as much for this exercise.

6.  Examine the health facilities dataset. Note that while this is an [authoratitive dataset made available by SC DHE](https://sc-department-of-health-and-environmental-control-gis-sc-dhec.hub.arcgis.com/datasets/04d86b6899fc450288ba07d0dcab2d73_0/explore?location=34.310761%2C-90.432550%2C5.21), it may not be directly usable for our analysis. Hence, before we can use this data, we need to make sure that we only include the relevant health facilties that are useful for our analysis.

#### Select by Expression

7.  First you will try to narrow down the number of health facilities that are registered in SC and are not tattoo or body piercing facilities. You can do so in multiple ways, but you will need to use the [**Select by Expression**]{.underline} tool in some way. You need to select health facilities whose `"PERMIT_TYPE"` is not `'HLBODYPIERCINGFAC`' or `'HLTATTOOFAC'`. In addition, you also need to select facilities whose `"LE_STATE_CODE"` is `'SC'`.

[Q2.]{style="color: red;"}

-   [Describe the process of subsetting your desired health facilities, including the exact expression(s) that you provided to [**Select by Expression**]{.underline} tool. You can also breakdown your expressions and use 'add to selection', or use 'invert selection' as needed. Make sure to describe your process. Do not clear your selections as you will need them for your next question too.]{style="color: red;"}

-   [How many facilities (out of 3185) did you end up selecting?]{style="color: red;"}

#### Select By Location

[Q3.]{style="color: red;"}

-   [You will notice that there there are some facilties outside SC boundaries that have also been selected due to geocoding errors. To further refine our selection use the [**Select by Location**]{.underline} tool under Vector -\> Research Tools. Copy paste a screenshot of your Select by Location window with your parameters.]{style="color: red;"}

-   [How many facilities (out of 3185) did you end up selecting? These final selected facilities should be slightly lower than the ones that were selected in the previous question to account for out of state facilities]{style="color: red;"}

8.  Export the selected features to a new file called `hf_selected.gpkg.` Makes sure to choose the correct projection (NAD 83/ EPSG: 4269).

### Converting Census Geometry to Centroid

9.  Before we calculate which census BGs are within 5 miles of a health facility we will first convert them from a polygon to their geometric centroids. Go to **Vector -\> Geometry Tools -\> Centroids**. Check [*'Create centroid for each part*]{.underline}'. Save the file as `'bg_centroids.gpkg'`. Note that census tiger files have internal centroid coordinates stored as INTPLAT and INTPLON that can be used to create more accurate geometric centroids. But we do not need to worry about them here. MMQGIS also has functionality to create centroids.

    [Q4.Why would we need to convert census BGs to centroids for our purpose rather than leaving them as polygons? What could be a potential limitation of using geometric centroids in this case? What could be a better way to measure a central feature that may be more representative? Answer in 3-5 sentences. It is ok if you do not have a perfect answer but think creatively and give it your best shot, as this would be an important workflow for your final projects.]{style="color: red;"}

10. There is a quirk in QGIS where the coordinate system may get undefined for the newly created centroids. To fix that, **right click on `bg_centroids` layer –\> Layer CRS -\> select 'EPSG:4269 NAD 83'**.

### Reprojecting and Buffering

10. Before we create 5km buffers for health facilities, we need to project our data into a projected coordinate system. Change the CRS of `hf_selected` to **EPSG:32133 (SC Lambert Conformal Conic)** and save the new file as `hf_selected_proj.gpkg`

    [Q5.Why did we need to change the CRS? What could have potentially happened if we had not changed the CRS to a projected coordinate system? Think about the implications of the units of a Geographical coordinate system vs projected coordinate system. (1-2 sentences)]{style="color: red;"}

11. Now, go to **Vector -\> Geoprocessing Tools -\> Buffer,** select `hf_selected_proj` as your input later, and distance as [5 kilometers or 5000 meters]{.underline}. Leave everything else as it is, and save the file as `'hf_5km.gpkg'`.

12. [**Optional: If you are confused about why we needed to change the CRS, try repeating 11. on the unprojected file `hf_selected` and see what happens.**]{.underline}

### Selecting centroids within 5km of a Health Facility

13. Before we select the centroids, reproject `bg_centroids` to the same CRS (EPSG: 32133) and name the file as `bg_centroids_proj.gpkg`.

14. Now use the **'Select by Location'** tool, to select all census BG centroids that are within 5km of a health facility.

    [Q6.How many census BGs (out of 3417) are within 5km of a health facility?]{style="color: red;"}

15. Clear your selection, and select centroids using the **'Select within distance'** tool.

    [Q7.How many census BGs (out of 3417) are within 5km of a health facility based on this tool? Is this number the same as the selection from Q6?]{style="color: red;"} Do not clear this selection as this will be used in the next steps.

    [Extra Credit. Why might there be a difference in the number of centroids selected between the 2 methods?]{style="color: red;"}

### Calculating Proportion of Disadvantaged Populations within 5km of Health Facility

16. Use the Show Statistical Summary tool on the selected features from `bg_centroid_proj`, and choose the **`"sc_bg_demographics_poc_perc"`** field.

    [Q8. Examine the mean statistic. Report the value of the mean statistic. What does the value mean? Explain in 1-2 sentences.]{style="color: red;"}

17. Using field calculator, create a new field called n_disadv that calculates the number of disadvantaged populations in each BG. [**Uncheck the 'Only update selected features'**]{.underline} checkbox. Keep the output type as **Integer 32 bit**. In the Expression Editor, enter the following query and press ok.

    `round("sc_bg_demographics_total_pop" * ("sc_bg_demographics_poc_perc" /100))`

18. To make the new edits permanent, save the edits using the floppy drive icon in the top right (after the 2 pencil icons). Then click the yellow pencil icon to toggle off editing.

19. Use the Show Statistical Summary tool on the **selected features** from `bg_centroid_proj`, and choose the **"`n_disadv"`**field.

    [Q9 a) . Examine the Sum statistic. Report the value of the sum statistic.b) Now choose the**"sc_bg_demographics_total_pop"** field and report the value of the sum statistic.]{style="color: red;"}

20. Using any calculator (windows/mac have one or you can also use the internet), do the following calculation:

    **`(Q9a / Q9b)*100`**

    [Q 10) Report your answer. Is this number different than what you got in Q 8)? What does this number mean? Which one would you use to calculate the percentage of disadvantaged populations within 5 km of health facility and why?]{style="color: red;"}

21. Submit your word file with all your answers to your respective OneDrive folder.
