---
title: 'Introduction to SaTScan'
author:
- In Class Demonstration \#8 \newline
- GEOG 510, GIS and Spatial Analysis in Public Health \newline
- Varun Goel
output:
  html_document:
    theme: flatly
    highlight: tango
    mathjax: null
---

```{css, echo=FALSE}
a {
  color: royalblue;
}

a:hover {
  color: darkorange;
}

div.highlightblock { 
 background-color: #e0f0ff; 
 padding: 5px 10px 4px 10px;
}
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

------------------------------------------------------------------------

This exercise walks you through a cluster analysis in **SaTScan**. If you have not installed SaTScan on your computer, do so now (for instructions, see the Software Document on Canvas).

If you want to follow along, the [data are located here](https://drive.google.com/file/d/1GEp27zWzFdr7cZId6ad0X4nlVMzCkica/view?usp=sharing). We will be working with the Lyme Disease incidence data for this demonstration.

**Note that throughout this document, if I use the term "right click," this means "control click" for Mac users!**

------------------------------------------------------------------------

### Prepare SaTScan

1.  Open SaTScan and choose [Create New Session]{.underline}. Navigate to the [Analysis tab]{.underline}. We are working with cross-sectional data, so we will be performing a **Purely Spatial Analysis**. Our probability model is **Poisson** because we are working with Lyme Disease cases. In this case, we want to scan only for clusters having **High Rates**.
2.  Click on the Advanced button and navigate to the Spatial Window tab. This is where you can set the [“maximum” spatial size]{.underline} of the identified clusters and can choose between [Circular]{.underline} and [Elliptic]{.underline} cluster shapes. For this analysis, we will keep things simple and leave them on their default values, but knowing where to change these values is important. Click Close.
3.  Click the Input tab. Here we have to import a Case File. We will use the **.dbf file** (attribute table) from a shapefile version of the Lyme Disease data. Click the button with the three little dots for Case File and select **`NC_ZIP_Lyme_2016_2018.dbf`**. Click Next. In the popup window:

-   Choose [ZIP_CODE]{.underline} for Location or Identifier
-   Choose [CASES]{.underline} for Number of Cases
-   Click Next, then click Next again
-   Save the imported input file as `NC_ZIP_Lyme_2016_2018.cas`, then click Import.

4.  Click the button with the three little dots for Population File and select `NC_ZIP_Lyme_2016_2018.dbf`. Click Next. In the popup window:

-   Choose [ZIP_CODE]{.underline} for Location or Identifier
-   Choose [POP20]{.underline} for Population
-   Click Next, then click Next again
-   Save the imported input file as `NC_ZIP_Lyme_2016_2018.pop`, then click Import.

5.  Click the button with the three little dots for Coordinates File and select `NC_ZIP_Lyme_2016_2018.shp`. Click Next. SaTScan loves working with geographic point data, so it calculates the centroids of the polygons for you. In the popup window:

-   Change the top option to [Cartesian]{.underline} ...
-   Choose [ZIP_CODE]{.underline} for Location or Identifier
-   Choose [Longitude / X for X and Latitude / Y for Y]{.underline}
-   Click Next, then click Next again
-   Save the imported input file as `NC_ZIP_Lyme_2016_2018.geo`, then click Import.

6.  Click on the Output tab. Write the Main Results File to `NC_ZIP_Lyme_2016_2018_Clusters.txt`. Make sure the little boxes are [selected for all options under dBase]{.underline}. Click on [Advanced and explore options (especially overlap!)]{.underline}.

------------------------------------------------------------------------

### Run SaTScan

7.  To run SaTScan, click the little green triangle button (near the top of the main SaTScan window). Another way to do this is to go to the top menu and choose Session execute.

When SaTScan is done, NC_ZIP_Lyme_2016_2018_Clusters.txt will pop up. This file contains some basic information about the input data and resulting clusters, as well as the members of and statistics for each cluster. Scroll to the top and note the nature of the output. In this case, we want to map our output, so we will be working in QGIS to do that. See the SaTScan Users Guide for more detailed information about the potential output options and what is included in each file. Prior to closing SaTScan, save your session.

------------------------------------------------------------------------

### Create Mappable Data from SaTScan

8.  Open QGIS and create a new project. Add `NC_ZIP_Lyme_2016_2018.shp`. Diplay [Case Rate]{.underline} variable.
9.  Add `NC_ZIP_Lyme_2016_2018_Clusters.col.dbf` to the QGIS Layers panel (you can drag/drop). This file contains information about the center, size, and statistical attributes of each of the clusters identified in SaTScan.
10. Create a temporary point layer of the cluster centers. In the Processing Toolbox, navigate to [Vector creation \| Create points layer from tabl]{.underline}e. For the Input layer choose `NC_ZIP_Lyme_2016_2018_Clusters.col`. Select the appropriate fields for X (X) and Y (Y), and [make sure that the CRS is EPSG:32119]{.underline} click OK. These are the center points of the clusters.
11. Open the attribute table of the output. Note that some "clusters" are single observations. Also, note that the p-value for some of the clusters is above our general threshold for statistical significance.
12. Use an attribute query to select only points with a RADIUS greater than 0 and a p-value less than or equal to 0.05.
13. to [Vector \| Geoprocessing Tools \| Buffer]{.underline}. For Input layer, choose the “Points from table” file. **Make sure that Selected features only is checked!** For Distance, click the little button all the way to the right (next to the word meters) and choose Field type: ... \| RADIUS (**this is the variable distance!**). Leave everything else on the default value (including Dissolve result), and then click Run.
14. Install and activate the "Select Within" plugin. Go to Vector \| Select Within \| Select Within. Use this tool to select and then export the Zip Codes falling within the high clusters. Use the Centroid option. **We use this selection method because centroids are what were used to define the clusters in SaTScan!**
15. In case you have issues creating files in this demo, you can also [download the data with all generated files from this demo here](https://drive.google.com/file/d/1Im1FIhPsf-lNtjN4tUVe7RtwW2e6tQoD/view?usp=sharing).

------------------------------------------------------------------------
